cws:
  template: ci/dynamic-build/cws.tpl.yml
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  changed:
    - pkg/ebpf/**/*
    - pkg/security/**/*
    - test/kitchen/site-cookbooks/dd-security-agent-check/**/*
    - test/kitchen/test/integration/security-agent-test/**/*
    - test/kitchen/test/integration/security-agent-stress/**/*