cws:
  template: ci/dynamic-build/cws.tpl.yml
  variables:
    DD_AGENT_TESTING_DIR: $DD_AGENT_TESTING_DIR
  changed:
    - pkg/ebpf/**/*
    - pkg/security/**/*
    - test/kitchen/site-cookbooks/dd-security-agent-check/**/*
    - test/kitchen/test/integration/security-agent-test/**/*
    - test/kitchen/test/integration/security-agent-stress/**/*