stages:
  - generate
  - trigger

variables:
  DATADOG_AGENT_BUILDIMAGES_SUFFIX: "_test_only"
  DATADOG_AGENT_BUILDIMAGES: v19999662-f999256

generate_pipeline:
  stage: generate
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64$DATADOG_AGENT_BUILDIMAGES_SUFFIX:$DATADOG_AGENT_BUILDIMAGES
  tags:
  - arch:amd64
  script:
    - source /root/.bashrc
    - pip install oyaml
    - inv commands.dynamic-run
    - ls dynamic/
  needs: []
  artifacts:
    paths:
      - .dynamic.yml
      - .gitlab/*

trigger_pipeline:
  stage: trigger
  needs:
    - job: generate_pipeline
      artifacts: true
  trigger:
    include:
      - local: .dynamic.yml


