---
generate-pipeline:
  stage: build
  tags:
    - "arch:amd64"
  image: registry.ddbuild.io/images/mirror/python:3.9
  script:
    - pip install gcip
    - python .gitlab-ci.py
  artifacts:
    paths:
      - generated-config.yml

run-pipeline:
  stage: deploy
  needs:
    - generate-pipeline
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-pipeline
    strategy: depend
