stages:
  - generate
  - trigger

variables:
  DATADOG_AGENT_BUILDIMAGES_SUFFIX: ""
  DATADOG_AGENT_BUILDIMAGES: v19867666-abda994

generate_pipeline:
  stage: generate
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64$DATADOG_AGENT_BUILDIMAGES_SUFFIX:$DATADOG_AGENT_BUILDIMAGES
  tags:
  - arch:amd64
  before_script:
    - pip install -r requirements.txt
  script:
    - inv commands.dynamic-run
  needs: []
  artifacts:
    paths:
      - .dynamic.yml
      - .gitlab/*

trigger_pipeline:
  stage: trigger
  needs:
    - job: generate_pipeline
      artifacts: true
  trigger:
    include:
      - local: .dynamic.yml


