receivers:
  zipkin:
  filelog:
    include_file_path: true
    poll_interval: 500ms
    include:
      - /var/log/**/*example*/*.log


exporters:
  otlp:
    endpoint: localhost:4317
  logging:

extensions:
  trace:
    api:
      key: $DD_API_KEY


service:
  extensions: trace
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [otlp]

    traces:
      receivers: [zipkin]
      exporters: [otlp]
