stages:
  - build
  - test

# std lib

.manual:
  - when: manual
    allow_failure: true

.kitchen_common:
  stage: kitchen_testing
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/dd-agent-testing:$DATADOG_AGENT_BUILDIMAGES
  tags: ["arch:amd64"]
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - $CI_PROJECT_DIR/kitchen_logs
  retry: 1

.kitchen_azure:
  variables:
    KITCHEN_PROVIDER: azure

.kitchen_azure_x64:
  variables:
    KITCHEN_ARCH: x86_64
  extends:
    - .kitchen_azure

.kitchen_ec2:
  variables:
    KITCHEN_PROVIDER: ec2
    KITCHEN_EC2_IAM_PROFILE_NAME: ci-datadog-agent-e2e-runner

.kitchen_ec2_spot_instances:
  extends: .kitchen_ec2
  variables:
    KITCHEN_EC2_SPOT_PRICE: on-demand

.kitchen_ec2_arm64:
  variables:
    KITCHEN_ARCH: arm64
    KITCHEN_EC2_INSTANCE_TYPE: "t4g.xlarge"
    CHEF_VERSION: 14.15.6
  extends:
    - .kitchen_ec2_spot_instances

.kitchen_datadog_agent_flavor:
  variables:
    AGENT_FLAVOR: "datadog-agent"

.kitchen_azure_location_north_central_us:
  variables:
    AZURE_LOCATION: "North Central US"

.kitchen_ec2_location_us_east_1:
  variables:
    KITCHEN_EC2_REGION: us-east-1
    KITCHEN_EC2_SUBNET: subnet-c18341ed
    KITCHEN_EC2_SG_IDS: sg-0f5617ceb3e5a6c39

# end stdlib

.build_tests_ebpf_cws:
  stage: build
  needs: ["go_deps", "go_tools_deps"]
  artifacts:
    when: always
    paths:
      - $DD_AGENT_TESTING_DIR/site-cookbooks/dd-security-agent-check/files
  script:
    - inv -e install-tools
    - invoke -e security-agent.kitchen-prepare

build_x64:{{.Rule.Name}}:
  extends: .build_tests_ebpf_cws
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/system-probe_x64:$DATADOG_AGENT_SYSPROBE_BUILDIMAGES
  tags: ["runner:main"]
  variables:
    ARCH: amd64
  before_script:
    - !reference [.retrieve_linux_go_deps]
    - !reference [.retrieve_linux_go_tools_deps]
    - !reference [.retrieve_sysprobe_deps]

build_arm64:{{.Rule.Name}}:
  extends: .build_tests_ebpf_cws
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/system-probe_arm64:$DATADOG_AGENT_SYSPROBE_BUILDIMAGES
  tags: ["runner:docker-arm", "platform:arm64"]
  variables:
    ARCH: arm64
  before_script:
    - !reference [.retrieve_linux_go_deps]
    - !reference [.retrieve_linux_go_tools_deps]
    - !reference [.retrieve_sysprobe_deps]

.kitchen_test_security_agent:
  extends:
    - .kitchen_common
    - .kitchen_datadog_agent_flavor
  rules:
    !reference [.manual]
  stage: functional_test
  retry: 0
  variables:
    AGENT_MAJOR_VERSION: 7
    DD_PIPELINE_ID: $CI_PIPELINE_ID-a7
    CHEF_VERSION: 14.15.6
  script:
    - bash -l tasks/run-test-kitchen.sh security-agent-test $AGENT_MAJOR_VERSION

kitchen_test_security_agent_x64:
  extends:
    - .kitchen_test_security_agent
    - .kitchen_azure_x64
    - .kitchen_azure_location_north_central_us
  needs: ["build_tests_ebpf_cws_x64"]
  variables:
    KITCHEN_ARCH: x86_64
  before_script:
    - cd $DD_AGENT_TESTING_DIR
    - bash -l tasks/kitchen_setup.sh
  parallel:
    matrix:
      - KITCHEN_PLATFORM: "centos"
        KITCHEN_OSVERS: "centos-77,rhel-85"
      - KITCHEN_PLATFORM: "ubuntu"
        KITCHEN_OSVERS: "ubuntu-18-04-0,ubuntu-18-04,ubuntu-18-04-3"
      - KITCHEN_PLATFORM: "ubuntu"
        KITCHEN_OSVERS: "ubuntu-20-04,ubuntu-20-04-2,ubuntu-22-04"
      - KITCHEN_PLATFORM: "suse"
        KITCHEN_OSVERS: "sles-12,sles-15"
      - KITCHEN_PLATFORM: "suse"
        KITCHEN_OSVERS: "opensuse-15-3"
      - KITCHEN_PLATFORM: "debian"
        KITCHEN_OSVERS: "debian-10,debian-11"
      - KITCHEN_PLATFORM: "oracle"
        KITCHEN_OSVERS: "oracle-7-9"

kitchen_test_security_agent_arm64:
  extends:
    - .kitchen_test_security_agent
    - .kitchen_ec2_location_us_east_1
    - .kitchen_ec2_spot_instances
  rules:
    !reference [.on_security_agent_changes_or_manual]
  needs: [ "build_tests_ebpf_cws_arm64" ]
  variables:
    KITCHEN_ARCH: arm64
    KITCHEN_EC2_INSTANCE_TYPE: "t4g.xlarge"
  before_script:
    - cd $DD_AGENT_TESTING_DIR
    - bash -l tasks/kitchen_setup.sh
  parallel:
    matrix:
      - KITCHEN_PLATFORM: "ubuntu"
        KITCHEN_OSVERS: "ubuntu-20-04-2,ubuntu-22-04"

kitchen_test_security_agent_amazonlinux_x64:
  extends:
    - .kitchen_test_security_agent
    - .kitchen_ec2_location_us_east_1
    - .kitchen_ec2_spot_instances
  rules:
    !reference [.on_security_agent_changes_or_manual]
  needs: [ "build_tests_ebpf_cws_x64" ]
  variables:
    KITCHEN_ARCH: x86_64
    KITCHEN_EC2_INSTANCE_TYPE: "t2.medium"
  before_script:
    - cd $DD_AGENT_TESTING_DIR
    - bash -l tasks/kitchen_setup.sh
  parallel:
    matrix:
      - KITCHEN_PLATFORM: "amazonlinux"
        KITCHEN_OSVERS: "amazonlinux2-4-14,amazonlinux2-5-10"

kitchen_stress_security_agent:
  extends:
    - .kitchen_common
    - .kitchen_datadog_agent_flavor
    - .kitchen_azure_x64
    - .kitchen_azure_location_north_central_us
  rules:
    !reference [.manual]
  stage: functional_test
  needs: ["build_tests_ebpf_cws_x64"]
  variables:
    AGENT_MAJOR_VERSION: 7
    DD_PIPELINE_ID: $CI_PIPELINE_ID-a7
  before_script:
    - cd $DD_AGENT_TESTING_DIR
    - bash -l tasks/kitchen_setup.sh
  script:
    - bash -l tasks/run-test-kitchen.sh security-agent-stress $AGENT_MAJOR_VERSION
  parallel:
    matrix:
      - KITCHEN_PLATFORM: "ubuntu"
        KITCHEN_OSVERS: "ubuntu-20-04"
