name: "Windows unit tests"

on:
  push:
    branches:
      - main
      - 7.[0-9][0-9].x
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  windows-unit-tests:
    # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-2019
    steps:
      - name: Checkout datadog-agent repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #needed for 'git describe' to work

      - name: Run tests
        run: |
          docker run --rm -v "$(Get-Location):c:\mnt" datadog/agent-buildimages-windows_x64:1809 c:\mnt\tasks\winbuildscripts\unittests.bat
          If ($lastExitCode -ne "0") { throw "Previous command returned $lastExitCode" }
