name: "Windows Go linters"

on:
  push:
    branches:
      - main
      - 7.[0-9][0-9].x
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  windows-lint-go:
    runs-on: windows-2019 # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    steps:
      - name: Checkout datadog-agent repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #needed for 'git describe' to work

      - name: Run go linters
        run: |
          $buildimage = "v15101851-1eecc1f"
          docker run --rm -v "$(Get-Location):c:\mnt" datadog/agent-buildimages-windows_x64:1809-$buildimage c:\mnt\tasks\winbuildscripts\lint.bat
          If ($lastExitCode -ne "0") { throw "Previous command returned $lastExitCode" }
